// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iFHMS.DotnetCodingChallenge;

#nullable disable

namespace iFHMS.DotnetCodingChallenge.Migrations
{
    [DbContext(typeof(ChallengeDbContext))]
    [Migration("20220518153539_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");
#pragma warning restore 612, 618
        }
    }
}
